"use strict";

const ORDER_STATUS = Object.freeze({
    PENDING: 'PENDING',
    PROCESSING: 'PROCESSING',
    COMPLETED: 'COMPLETED',
    CANCELLED: 'CANCELLED',
});

const ERROR_CODES = Object.freeze({
    ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
    ORDER_EXISTS: 'ORDER_EXISTS',
    INVALID_ORDER_ID: 'INVALID_ORDER_ID',
    INVALID_ORDER_NAME: 'INVALID_ORDER_NAME',
    INVALID_PARAMS: 'INVALID_PARAMS',
});

export { ORDER_STATUS, ERROR_CODES }
