import { Order } from "../constants/constant";

const orders: Order[] = [
  {
    id: "ORD-7841",
    customer: "Halcyon Industrial",
    product: "Steel Shaft Bearings x200",
    date: "2026-03-18",
    amount: 4820,
    status: "PENDING",
    priority: "HIGH",
    urgent: true,
  },
  {
    id: "ORD-7840",
    customer: "Vertex Manufacturing",
    product: "CNC Tooling Kit #A4",
    date: "2026-03-18",
    amount: 1350,
    status: "PENDING",
    priority: "HIGH",
    urgent: true,
  },
  {
    id: "ORD-7839",
    customer: "NorCal Fab Works",
    product: "Hydraulic Seal Kit",
    date: "2026-03-17",
    amount: 620,
    status: "SHIPPED",
    priority: "MEDIUM",
    urgent: false,
  },
  {
    id: "ORD-7838",
    customer: "Delta Precision Co.",
    product: "Lathe Chuck Assembly",
    date: "2026-03-17",
    amount: 2180,
    status: "PROCESSING",
    priority: "MEDIUM",
    urgent: false,
  },
  {
    id: "ORD-7837",
    customer: "Ironbridge Supply",
    product: "Pneumatic Fittings x50",
    date: "2026-03-16",
    amount: 390,
    status: "COMPLETE",
    priority: "LOW",
    urgent: false,
  },
  {
    id: "ORD-7836",
    customer: "Summit Metal Works",
    product: "Drill Press V-Belt",
    date: "2026-03-16",
    amount: 145,
    status: "PENDING",
    priority: "MEDIUM",
    urgent: false,
  },
  {
    id: "ORD-7835",
    customer: "Pacific CNC Group",
    product: "End Mill Set - Carbide",
    date: "2026-03-15",
    amount: 870,
    status: "SHIPPED",
    priority: "HIGH",
    urgent: true,
  },
  {
    id: "ORD-7834",
    customer: "Atlas Hydraulics",
    product: "Pump Rebuild Kit 4L",
    date: "2026-03-15",
    amount: 1640,
    status: "COMPLETE",
    priority: "LOW",
    urgent: false,
  },
  {
    id: "ORD-7833",
    customer: "Ridgeline Tooling",
    product: "Thread Tap Set M6-M24",
    date: "2026-03-14",
    amount: 290,
    status: "CANCELLED",
    priority: "LOW",
    urgent: false,
  },
  {
    id: "ORD-7832",
    customer: "Cascade Fabrication",
    product: "Welding Wire 15kg Spool",
    date: "2026-03-14",
    amount: 520,
    status: "PENDING",
    priority: "MEDIUM",
    urgent: false,
  },
];

export { orders };
